---
- name: Check if cargo is installed
  ansible.builtin.stat:
    path: "{{ home }}/.cargo/bin/cargo"
  register: cargo_binary

- name: Download Rust installer
  when: not cargo_binary.stat.exists
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: true

- name: Install Rust
  when: not cargo_binary.stat.exists
  ansible.builtin.command:
    argv:
      - /tmp/sh.rustup.rs
      - -y
  args:
    creates: "{{ home }}/.cargo/bin/cargo"

- name: Check for Rust toolchain updates
  ansible.builtin.command:
    argv:
      - "{{ home }}/.cargo/bin/rustup"
      - check
  register: rustup_update_check
  changed_when: false
  when: cargo_binary.stat.exists

- name: Update Rust toolchains
  ansible.builtin.command:
    argv:
      - "{{ home }}/.cargo/bin/rustup"
      - update
  when:
    - cargo_binary.stat.exists
    - "'Update available' in rustup_update_check.stdout"

- name: Install cargo-update
  community.general.cargo:
    name: cargo-update
  register: cargo_update_install
  environment:
    PATH: "{{ home }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"
  failed_when: false
