---

- name: Check if cargo binary exists
  ansible.builtin.stat:
    path: "{{ home }}/.cargo/bin/cargo"
  register: cargo_binary

- name: Download Rust installer
  when: not cargo_binary.stat.exists
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: true

- name: Install Rust
  when: not cargo_binary.stat.exists
  ansible.builtin.command:
    argv:
      - /tmp/sh.rustup.rs
      - -y

- name: Update Rust
  when: cargo_binary.stat.exists
  ansible.builtin.command:
    argv:
      - "{{ home }}/.cargo/bin/rustup"
      - update
  changed_when: false

- name: Install "cargo-update"
  community.general.cargo:
    name: cargo-update
  environment:
    PATH: "{{ home }}/.cargo/bin:{{ ansible_env.PATH }}"
  ignore_errors: true

- name: Link rust config
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zsh/conf.d/rust.zsh"
    dest: "{{ home }}/.zsh/conf.d/rust.zsh"
    state: link

# https://waylonwalker.com/install-rust/
