---

- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    state: latest

- name: Create ~/.zsh
  ansible.builtin.file:
    path: "{{ home }}/.zsh"
    state: directory
    mode: '0755'

- name: Create ~/.zsh/plugin
  ansible.builtin.file:
    path: "{{ home }}/.zsh/plugin"
    state: directory
    mode: '0755'

- name: Link .zshenv
  ansible.builtin.file:
    src: "{{ dotfiles }}/zsh/.zshenv"
    dest: "{{ home }}/.zshenv"
    state: link

- name: Link zsh configs
  ansible.builtin.file:
    src: "{{ dotfiles }}/zsh/{{ item }}"
    dest: "{{ home }}/.zsh/{{ item }}"
    state: link
  loop:
    - .zshrc
    - alias.zsh
    - .dircolors

- name: Link zsh plugin configs
  ansible.builtin.file:
    src: "{{ dotfiles }}/zsh/plugin/{{ item }}"
    dest: "{{ home }}/.zsh/plugin/{{ item }}"
    state: link
  loop:
    - plugin.zsh
    - p10k.zsh
