---

- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: latest

- name: Create ~/.zsh
  ansible.builtin.file:
    path: "{{ home }}/.zsh"
    state: directory

- name: Link .zshenv
  ansible.builtin.file:
    src: "{{ dotfiles }}/zsh/.zshenv"
    dest: "{{ home }}/.zshenv"
    state: link

- name: Link zsh configs
  ansible.builtin.file:
    src: "{{ dotfiles }}/zsh/{{ item }}"
    dest: "{{ home }}/.zsh/{{ item }}"
    state: link
  loop:
    - .zshrc
    - alias.zsh
    - plugin.zsh
    - plugin.p10k.zsh
    - .dircolors
