---
- name: dotfiles
  hosts: all

  roles:
    - role: common
      tags:
        - common
        - minimum

    - role: git
      tags:
        - git
        - minimum

    - role: cli_tools
      tags:
        - cli_tools
        - extra

    - role: docker
      tags:
        - docker
        - extra

    - role: zsh
      tags:
        - zsh
        - minimum
        - install
        - link

    - role: fzf
      tags:
        - fzf
        - normal
        - install
        - link

    - role: tmux
      tags:
        - tmux
        - minimum
        - install
        - link

    - role: vim
      tags:
        - vim
        - minimum
        - install
        - link

    - role: neovim
      tags:
        - neovim
        - normal
        - install
        - link

    - role: C
      tags:
        - C
        - extra

    - role: rust
      tags:
        - rust
        - extra

    - role: mise
      tags:
        - mise
        - normal
        - install
        - link


    - role: uv
      tags:
        - python
        - extra
        - install
        - link

    - role: go
      tags:
        - go
        - extra
        - install
        - link
