---

- name: Install neovim
  become: true
  ansible.builtin.apt:
    name: neovim
    state: latest

- name: Create ~/.config/nvim
  ansible.builtin.file:
    path: "{{ home }}/.config/nvim"
    state: directory
    mode: "0755"

- name: Link neovim configs
  ansible.builtin.file:
    src: "{{ dotfiles }}/neovim/{{ item }}"
    dest: "{{ home }}/.config/nvim/{{ item }}"
    state: link
  loop:
    - init.vim
    - dein.toml
