---

- name: Update apt packages
  become: yes
  ansible.builtin.apt:
    update_cache: true
    upgrade: yes
    state: latest

- name: Install common packages
  become: yes
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - snapd
    state: latest

- name: Link .gitconfig
  ansible.builtin.file:
    src: "{{ dotfiles }}/git/.gitconfig"
    dest: "{{ home }}/.gitconfig"
    state: link
