---

  - name: Check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: true

  - name: Download Rust installer
    when: cargo_exists is failed
    ansible.builtin.get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'

  - name: Install Rust
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y

  - name: Update Rust
    when: cargo_exists is success
    shell: rustup update

  - name: Install "cargo-update"
    community.general.cargo:
      name: cargo-update

# https://waylonwalker.com/install-rust/
