---

- name: Install zsh (Linux)
  become: true
  ansible.builtin.package:
    name: zsh
    state: latest
  when: ansible_facts['system'] == 'Linux'

- name: Install zsh (macOS)
  community.general.homebrew:
    name: zsh
    state: latest
  when: ansible_facts['system'] == 'Darwin'
