---

- name: Install zsh
  become: true
  ansible.builtin.package:
    name: zsh
    state: latest

- name: Create zsh directories
  ansible.builtin.file:
    path: "{{ home }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - .zsh
    - .zsh/conf.d

- name: Link zsh config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
  loop:
    - .zshenv
    - .zsh/.zshrc
    - .zsh/.dircolors
    - .zsh/conf.d/00_powerlevel10k.zsh
    - .zsh/conf.d/alias.zsh
    - .zsh/conf.d/path.zsh
    - .zsh/conf.d/01_zinit.zsh
    - .zsh/conf.d/p10k.zsh
