---

- name: Install zsh for apt
  become: true
  when: ansible_pkg_mgr == "apt"
  ansible.builtin.apt:
    name: zsh
    state: latest

- name: Install zsh for dnf
  become: true
  when: ansible_pkg_mgr == "dnf"
  ansible.builtin.dnf:
    name: zsh
    state: latest

- name: Create ~/.zsh
  ansible.builtin.file:
    path: "{{ home }}/.zsh"
    state: directory
    mode: '0755'

- name: Link .zshenv
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zshenv"
    dest: "{{ home }}/.zshenv"
    state: link

- name: Link zsh configs
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zsh/{{ item }}"
    dest: "{{ home }}/.zsh/{{ item }}"
    state: link
  loop:
    - .zshrc
    - .dircolors
    - alias.zsh
    - p10k.zsh
    - path.zsh
    - zinit.zsh
