---

- name: Check if mise is installed
  ansible.builtin.stat:
    path: "{{ home }}/.local/bin/mise"
  register: mise_binary

- name: Download mise installer
  when: not mise_binary.stat.exists
  ansible.builtin.get_url:
    url: https://mise.run
    dest: /tmp/mise-install.sh
    mode: "0755"
    force: true

- name: Install mise
  when: not mise_binary.stat.exists
  ansible.builtin.command:
    argv:
      - /tmp/mise-install.sh
  args:
    creates: "{{ home }}/.local/bin/mise"
