---

- name: Check if mise binary exists
  ansible.builtin.stat:
    path: "{{ home }}/.local/bin/mise"
  register: mise_binary

- name: Install mise
  when: not mise_binary.stat.exists
  ansible.builtin.shell: curl https://mise.run | sh
  args:
    creates: "{{ home }}/.local/bin/mise"

- name: Update mise
  when: mise_binary.stat.exists
  ansible.builtin.command:
    argv:
      - "{{ home }}/.local/bin/mise"
      - self-update
  changed_when: false
