---

- name: Check if mise is installed
  ansible.builtin.shell: "command -v mise"
  register: mise_exists
  ignore_errors: true

- name: Install mise
  when: mise_exists is failed
  ansible.builtin.shell: "curl https://mise.run | sh"

- name: Update mise
  ansible.builtin.shell: "mise self-update"
