---

# ====== goenv ======

- name: Check if goenv is installed
  ansible.builtin.shell:
    "goenv -v"
  register: goenv_exists
  ignore_errors: true

- name: Install goenv
  when: goenv_exists is failed
  ansible.builtin.shell:
    "anyenv install goenv"
  environment:
    PATH: "{{ home }}/.anyenv/bin:{{ ansible_env.PATH }}"

# ====== go ======

- name: Check if go is installed
  ansible.builtin.shell:
    "go version"
  register: go_exists
  ignore_errors: true

- name: Install go
  when: go_exists is failed
  ansible.builtin.shell:
    "goenv install 1.20.1"

- name: Set global version
  when: go_exists is failed
  ansible.builtin.shell:
    "goenv global 1.20.1"
