---

# ====== goenv ======

- name: Check if goenv is installed
  ansible.builtin.shell:
    "goenv --version"
  register: goenv_exists
  ignore_errors: true

- name: Install goenv
  when: goenv_exists is failed
  ansible.builtin.shell:
    "anyenv install goenv"
  environment:
    PATH: "{{ home }}/.anyenv/bin:{{ ansible_env.PATH }}"

# ====== go ======

- name: Check if go {{ go_version }} is installed
  ansible.builtin.shell:
    "goenv versions | grep {{ go_version }}"
  register: go_exists
  ignore_errors: true

- name: Install go {{ go_version }}
  when: go_exists is failed
  ansible.builtin.shell:
    "goenv install {{ go_version }}"

- name: Set global version
  when: go_exists is failed
  ansible.builtin.shell:
    "goenv global {{ go_version }}"
