---
- name: Install git (Linux)
  become: true
  ansible.builtin.package:
    name: git
    state: present
  when: ansible_facts['system'] == 'Linux'

- name: Install git (macOS)
  community.general.homebrew:
    name: git
    state: latest
  when: ansible_facts['system'] == 'Darwin'

- name: Check if ghq is installed via mise
  ansible.builtin.command:
    argv:
      - "{{ home }}/.local/bin/mise"
      - where
      - ghq
  register: ghq_exists
  changed_when: false
  failed_when: false

- name: Install ghq via mise
  when: ghq_exists.rc != 0
  ansible.builtin.command:
    argv:
      - "{{ home }}/.local/bin/mise"
      - install
      - ghq
