---
- name: Link git files
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/apply_filetree.yml"
  vars:
    _filetree: fileLink
    _link_force_overrides:
      .gitconfig.local: false
