---

- name: Check if python {{ python_version }} is installed
  ansible.builtin.shell:
    "rtx list python | grep {{ python_version }}"
  register: python_exists
  ignore_errors: true

- name: Install python {{ python_version }}
  when: python_exists is failed
  ansible.builtin.shell:
    "rtx install python@{{ python_version }}"

- name: Set global version
  when: python_exists is failed
  ansible.builtin.shell:
    "rtx use -g python@{{ python_version }}"

# - name: Install pip3
#   become: true
#   ansible.builtin.apt:
#     name: python3-pip
#     state: latest

# ====== poetry ======

- name: Check if poetry is installed
  ansible.builtin.shell:
    "poetry --version"
  register: poetry_exists
  ignore_errors: true

- name: Install poetry
  when: poetry_exists is failed
  ansible.builtin.shell:
    "curl -sSL https://install.python-poetry.org | python3 -"

- name: Set poetry config
  ansible.builtin.shell:
    "poetry config virtualenvs.in-project true"
