---

- name: Install C/C++ packages
  become: true
  ansible.builtin.package:
    name:
      - "{{ 'build-essential' if ansible_pkg_mgr == 'apt' else '@Development tools' }}"
      - gdb
      - clang
      - lldb
      - cmake
    state: latest