---

- name: Install C/C++ packages (Linux)
  become: true
  ansible.builtin.package:
    name:
      - "{{ 'build-essential' if ansible_pkg_mgr == 'apt' else '@Development tools' }}"
      - gdb
      - clang
      - lldb
      - cmake
    state: latest
  when: ansible_facts['system'] == 'Linux'

- name: Install C/C++ packages (macOS)
  community.general.homebrew:
    name:
      - gdb
      - llvm
      - cmake
    state: latest
  when: ansible_facts['system'] == 'Darwin'
