---

- name: Install exa
  community.general.cargo:
    name: eza

- name: Install git-delta
  community.general.cargo:
    name: git-delta

- name: Install bat
  ansible.builtin.apt:
    name: bat
    state: latest
