---

- name: Check if uv binary exists
  ansible.builtin.stat:
    path: "{{ home }}/.local/bin/uv"
  register: uv_binary

- name: Install uv
  when: not uv_binary.stat.exists
  ansible.builtin.shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    creates: "{{ home }}/.local/bin/uv"

- name: Update uv
  when: uv_binary.stat.exists
  ansible.builtin.command:
    argv:
      - "{{ home }}/.local/bin/uv"
      - self
      - update
  changed_when: false
