---

- name: Check if uv is installed
  ansible.builtin.stat:
    path: "{{ home }}/.local/bin/uv"
  register: uv_binary

- name: Download uv installer
  when: not uv_binary.stat.exists
  ansible.builtin.get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/uv-install.sh
    mode: "0755"
    force: true

- name: Install uv
  when: not uv_binary.stat.exists
  ansible.builtin.command:
    argv:
      - /tmp/uv-install.sh
  args:
    creates: "{{ home }}/.local/bin/uv"

- name: Update uv
  when: uv_binary.stat.exists
  ansible.builtin.command:
    argv:
      - "{{ home }}/.local/bin/uv"
      - self
      - update
