---

- name: Check if uv is installed
  ansible.builtin.shell: command -v uv
  register: uv_exists
  ignore_errors: true

- name: Install uv
  when: uv_exists is failed
  ansible.builtin.shell: curl -LsSf https://astral.sh/uv/install.sh | sh

- name: Update uv
  ansible.builtin.shell: "uv self update"

- name: Link uv zsh config
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zsh/conf.d/uv.zsh"
    dest: "{{ home }}/.zsh/conf.d/uv.zsh"
    state: link
