---

- name: Install tmux (Linux)
  become: true
  ansible.builtin.package:
    name: tmux
    state: latest
  when: ansible_facts['system'] == 'Linux'

- name: Install tmux (macOS)
  community.general.homebrew:
    name: tmux
    state: latest
  when: ansible_facts['system'] == 'Darwin'

- name: Clone tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ home }}/.tmux/plugins/tpm"
    version: master
