---

- name: Install tmux
  become: true
  ansible.builtin.package:
    name: tmux
    state: latest

- name: Clone tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ home }}/.tmux/plugins/tpm"
    version: master
