---

- name: Ensure mise conf.d directory exists
  ansible.builtin.file:
    path: "{{ home }}/.config/mise/conf.d"
    state: directory
    mode: "0755"

- name: Render node mise config
  ansible.builtin.template:
    src: ".config/mise/conf.d/node.toml.j2"
    dest: "{{ home }}/.config/mise/conf.d/node.toml"
    mode: "0644"
