---

- name: Install vim
  become: true
  ansible.builtin.apt:
    name: vim
    state: latest

- name: Create ~/.vim
  ansible.builtin.file:
    path: "{{ home }}/.vim"
    state: directory
    mode: "0755"

- name: Link .vimrc
  ansible.builtin.file:
    src: "{{ dotfiles }}/vim/vimrc"
    dest: "{{ home }}/.vim/vimrc"
    state: link
