- name: Install common packages
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/install_os_packages.yml"
  vars:
    _package_manager_packages: "{{ common_package_manager_packages }}"
