---

- name: Update apt packages in Debian
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    state: latest
  when: ansible_facts["os_family"] == "Debian"

- name: Update apt packages in RedHat
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    state: latest
  when: ansible_facts["os_family"] == "RedHat"

- name: Install common packages
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - snapd
      - libssl-dev
    state: latest

- name: Link .gitconfig
  ansible.builtin.file:
    src: "{{ role_path }}/files/.gitconfig"
    dest: "{{ home }}/.gitconfig"
    state: link
    force: true
