---
- name: Docker | repository dependencies
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/install_os_packages.yml"
  vars:
    _package_manager_packages: "{{ docker_repository_dependency_packages }}"
    _package_state: present

- name: Docker | apt gpg key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Docker | apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64] https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Docker | dnf repository
  become: true
  ansible.builtin.command:
    argv:
      - dnf
      - config-manager
      - --add-repo
      - https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_pkg_mgr == 'dnf'

- name: Docker | packages
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/install_os_packages.yml"
  vars:
    _package_manager_packages: "{{ docker_package_manager_packages }}"
    _package_state: present

- name: Docker | service
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
