---

- name: Install neovim for apt
  become: true
  when: ansible_pkg_mgr == "apt"
  ansible.builtin.apt:
    name: neovim
    state: latest

- name: Install neovim for dnf
  become: true
  when: ansible_pkg_mgr == "dnf"
  ansible.builtin.dnf:
    name: neovim
    state: latest

- name: Create ~/.config/nvim
  ansible.builtin.file:
    path: "{{ home }}/.config/nvim"
    state: directory
    mode: "0755"

- name: Link neovim configs
  ansible.builtin.file:
    src: "{{ role_path }}/files/.config/nvim/{{ item }}"
    dest: "{{ home }}/.config/nvim/{{ item }}"
    state: link
  loop:
    - init.vim
    - dein.toml
